#!/usr/bin/env python3
"""
Generate all 100 Loop prompt files in Chinese and English.
This script defines all Loop metadata and generates individual markdown files.

⚠️  WARNING — DO NOT RUN BLINDLY  ⚠️
=====================================
The files in prompts/zh/ and prompts/en/ have been HAND-ENHANCED to the full
8-section structure (目标 / 适用场景 / 检查命令 / 退出条件 / 执行步骤 / 常见陷阱 /
注意事项 / 推荐代理). The templates below only generate the OLD 5-section minimal
structure.

Running `main()` will WIPE prompts/en/ and prompts/zh/ and overwrite every file
with the minimal version, DESTROYING the hand-written content.

This script is kept ONLY as a legacy bootstrap for generating brand-new Loops
from scratch. To protect the existing files, main() refuses to run unless the
environment variable LOOPS_REGENERATE=1 is set.
=====================================
"""

import os
import sys

# Category translations
CATEGORY_ZH = {
    "Testing": "测试",
    "CI/CD": "持续集成/持续部署",
    "Code Quality": "代码质量",
    "API/Specs": "API/规范",
    "Dependencies": "依赖管理",
    "Security": "安全",
    "Development Process": "开发流程",
    "Documentation": "文档",
    "Performance": "性能",
    "Accessibility": "无障碍",
    "Pull Request": "Pull Request",
    "Deployment": "部署",
    "Maintenance": "维护",
    "Git Hooks": "Git钩子",
    "Code Generation": "代码生成与重构",
    "Database": "数据库与数据",
    "Frontend": "前端与UI",
    "Backend": "后端与API开发",
    "Data Science": "数据科学与分析",
    "Content Creation": "内容创作与写作",
    "Product & Design": "产品与设计",
    "Operations & Marketing": "运营与市场",
    "Learning & Knowledge": "学习与知识管理",
    "Productivity": "效率与生产力",
    "System & DevOps": "系统与DevOps",
    "Security & Compliance": "安全与合规",
}

# All 100 loops
ALL_LOOPS = [
    # === Original 40 Loops ===
    # Testing (7)
    {
        "slug": "test-until-green",
        "title_en": "Test Until Green",
        "title_zh": "测试直到通过",
        "category": "Testing",
        "goal_en": "all tests pass",
        "goal_zh": "所有测试通过",
        "check_cmd": "npm test",
        "exit_when_en": "tests exit 0",
        "exit_when_zh": "测试退出码为0",
        "steps_en": "Step 1: Run tests. If there are failures, fix the smallest root cause, then repeat.",
        "steps_zh": "Step 1: 运行测试。如果有失败，修复最小的根因，然后重复。",
        "max_iterations": "10",
    },
    {
        "slug": "e2e-until-green",
        "title_en": "E2E Until Green",
        "title_zh": "E2E测试直到通过",
        "category": "Testing",
        "goal_en": "E2E test suite passes",
        "goal_zh": "E2E测试套件通过",
        "check_cmd": "npm run test:e2e",
        "exit_when_en": "E2E tests exit 0",
        "exit_when_zh": "E2E测试退出码为0",
        "steps_en": "Step 1: Run E2E tests. Fix the first failing spec, then repeat until all pass.",
        "steps_zh": "Step 1: 运行E2E测试。修复第一个失败的spec，然后重复直到全部通过。",
        "max_iterations": "10",
    },
    {
        "slug": "flaky-test-triage",
        "title_en": "Flaky Test Triage",
        "title_zh": "Flaky测试分类",
        "category": "Testing",
        "goal_en": "classify failing tests as flaky or real",
        "goal_zh": "将失败测试分类为flaky或real",
        "check_cmd": "npm test -- --testPathPattern=<failing-suite>",
        "exit_when_en": "each failure is classified",
        "exit_when_zh": "每个失败测试已分类",
        "steps_en": "Step 1: Rerun failing test suite multiple times. Classify each failure. Fix real issues.",
        "steps_zh": "Step 1: 多次运行失败的测试套件。对每个失败进行分类。修复真实问题。",
        "max_iterations": "8",
    },
    {
        "slug": "visual-regression-until-match",
        "title_en": "Visual Regression Until Match",
        "title_zh": "视觉回归直到匹配",
        "category": "Testing",
        "goal_en": "visual regression suite passes with intentional UI only",
        "goal_zh": "视觉回归测试通过，仅保留有意的UI变更",
        "check_cmd": "npx playwright test --grep @visual",
        "exit_when_en": "visual tests exit 0",
        "exit_when_zh": "视觉测试退出码为0",
        "steps_en": "Step 1: Run visual tests. Fix unintended UI diffs; update baselines only for deliberate design changes.",
        "steps_zh": "Step 1: 运行视觉测试。修复无意的UI差异；只为有意的设计变更更新基准。",
        "max_iterations": "6",
    },
    {
        "slug": "coverage-until-threshold",
        "title_en": "Coverage Until Threshold",
        "title_zh": "覆盖率直到达标",
        "category": "Testing",
        "goal_en": "coverage threshold met (default 80%)",
        "goal_zh": "覆盖率达标（默认80%）",
        "check_cmd": "npm test -- --coverage",
        "exit_when_en": "coverage meets threshold",
        "exit_when_zh": "覆盖率达标",
        "steps_en": "Step 1: Run coverage tests. Add targeted tests for the largest uncovered gaps.",
        "steps_zh": "Step 1: 运行覆盖率测试。为最大的未覆盖缺口添加针对性测试。",
        "max_iterations": "10",
    },
    {
        "slug": "staging-smoke-test",
        "title_en": "Staging Smoke Test",
        "title_zh": "预发布冒烟测试",
        "category": "Testing",
        "goal_en": "staging smoke tests pass",
        "goal_zh": "预发布环境冒烟测试通过",
        "check_cmd": "npm run smoke:staging",
        "exit_when_en": "staging smoke tests exit 0",
        "exit_when_zh": "预发布环境冒烟测试退出码为0",
        "steps_en": "Step 1: Run staging smoke test checklist. Fix the first failing item.",
        "steps_zh": "Step 1: 运行预发布环境冒烟测试清单。修复第一个失败项。",
        "max_iterations": "5",
    },
    {
        "slug": "post-edit-test-guard",
        "title_en": "Post-Edit Test Guard",
        "title_zh": "编辑后测试守卫",
        "category": "Testing",
        "goal_en": "related tests must pass after edits",
        "goal_zh": "编辑后相关测试必须通过",
        "check_cmd": "npm test -- --findRelatedTests <files>",
        "exit_when_en": "related tests pass",
        "exit_when_zh": "相关测试通过",
        "steps_en": "Step 1: Run related tests after edits. Fix failures before continuing.",
        "steps_zh": "Step 1: 编辑后运行相关测试。修复失败后再继续。",
        "max_iterations": "3",
    },
    # CI/CD (9)
    {
        "slug": "ship-pr-until-green",
        "title_en": "Ship PR Until Green",
        "title_zh": "Ship PR直到通过",
        "category": "CI/CD",
        "goal_en": "PR is open with all CI checks passing",
        "goal_zh": "PR已打开且所有CI检查通过",
        "check_cmd": "gh pr checks",
        "exit_when_en": "all CI checks pass",
        "exit_when_zh": "所有CI检查通过",
        "steps_en": "Step 1: Implement changes. Test locally. Push. Open PR. Fix CI until all checks pass.",
        "steps_zh": "Step 1: 实现变更。本地测试。推送。打开PR。修复CI直到全部通过。",
        "max_iterations": "15",
    },
    {
        "slug": "fix-ci-until-green",
        "title_en": "Fix CI Until Green",
        "title_zh": "修复CI直到通过",
        "category": "CI/CD",
        "goal_en": "latest CI run on current branch passes",
        "goal_zh": "当前分支的最新CI运行通过",
        "check_cmd": "gh run list ...",
        "exit_when_en": "CI run exits 0",
        "exit_when_zh": "CI运行退出码为0",
        "steps_en": "Step 1: Find latest failing CI run. Read logs. Reproduce locally. Fix root cause. Push. Verify.",
        "steps_zh": "Step 1: 找到最新失败的CI运行。读取日志。本地复现。修复根因。推送。验证。",
        "max_iterations": "10",
    },
    {
        "slug": "ci-failure-watcher",
        "title_en": "CI Failure Watcher",
        "title_zh": "CI失败监控",
        "category": "CI/CD",
        "goal_en": "latest CI run on current branch is green",
        "goal_zh": "当前分支的最新CI运行是绿色的",
        "check_cmd": "gh run list ...",
        "exit_when_en": "CI run is green",
        "exit_when_zh": "CI运行是绿色的",
        "steps_en": "Step 1: Check CI status. If failing, read logs, fix root cause, push if needed.",
        "steps_zh": "Step 1: 检查CI状态。如果失败，读取日志、修复根因、必要时推送。",
        "max_iterations": "10",
    },
    {
        "slug": "build-until-green",
        "title_en": "Build Until Green",
        "title_zh": "构建直到成功",
        "category": "CI/CD",
        "goal_en": "production build succeeds",
        "goal_zh": "生产构建成功",
        "check_cmd": "npm run build",
        "exit_when_en": "build exits 0",
        "exit_when_zh": "构建退出码为0",
        "steps_en": "Step 1: Run build. If it fails, fix the first error, then repeat until success.",
        "steps_zh": "Step 1: 运行构建。如果失败，修复第一个错误，然后重复直到成功。",
        "max_iterations": "5",
    },
    {
        "slug": "pre-commit-guard",
        "title_en": "Pre-Commit Guard",
        "title_zh": "Pre-commit守卫",
        "category": "CI/CD",
        "goal_en": "tests fail at commit time to block git commit",
        "goal_zh": "测试失败时阻止git提交",
        "check_cmd": "npm test",
        "exit_when_en": "tests exit 0 to allow commit",
        "exit_when_zh": "测试退出码为0才允许提交",
        "steps_en": "Step 1: Run tests before each git commit. Fix failures before committing.",
        "steps_zh": "Step 1: 在每次git提交前运行测试。修复失败后再提交。",
        "max_iterations": "3",
    },
    {
        "slug": "pr-self-review",
        "title_en": "PR Self Review",
        "title_zh": "PR自我审查",
        "category": "CI/CD",
        "goal_en": "three clean self-reviews on current diff",
        "goal_zh": "当前diff上完成三轮干净的自我审查",
        "check_cmd": "git diff main...HEAD",
        "exit_when_en": "no issues found in three reviews",
        "exit_when_zh": "三轮审查均无问题",
        "steps_en": "Step 1: Review diff like a senior reviewer. Fix found issues, then re-review.",
        "steps_zh": "Step 1: 像资深审查员一样审查diff。修复发现的问题，然后重新审查。",
        "max_iterations": "6",
    },
    {
        "slug": "pr-babysitter",
        "title_en": "PR Babysitter",
        "title_zh": "PR保姆",
        "category": "CI/CD",
        "goal_en": "PRs labeled codex-watch stay healthy",
        "goal_zh": "标记为codex-watch的PR保持健康",
        "check_cmd": 'gh pr list --label "codex-watch"',
        "exit_when_en": "no blocking CI failures",
        "exit_when_zh": "无阻塞CI失败",
        "steps_en": "Step 1: List watched PRs. Fix CI. Rebase stale PRs. Comment on stale items.",
        "steps_zh": "Step 1: 列出监控的PR。修复CI。rebase过期的PR。评论过期项。",
        "max_iterations": "10",
    },
    {
        "slug": "pr-watch-loop",
        "title_en": "PR Watch Loop",
        "title_zh": "PR监控循环",
        "category": "CI/CD",
        "goal_en": "codex-watch PRs stay healthy and unblocked",
        "goal_zh": "codex-watch PR保持健康且无阻碍",
        "check_cmd": "gh pr list --label codex-watch ...",
        "exit_when_en": "no blocking issues",
        "exit_when_zh": "无阻塞问题",
        "steps_en": "Step 1: List codex-watch PRs. Check CI and reviews. Report or fix simple blockers.",
        "steps_zh": "Step 1: 列出codex-watch PR。检查CI和reviews。报告或修复简单的阻碍。",
        "max_iterations": "10",
    },
    {
        "slug": "spec-first-ship",
        "title_en": "Spec-First Ship",
        "title_zh": "Spec优先发布",
        "category": "CI/CD",
        "goal_en": "every requirement in spec.md is implemented and checked",
        "goal_zh": "spec.md中的每个需求都已实现并打勾",
        "check_cmd": "npm test",
        "exit_when_en": "all spec items checked",
        "exit_when_zh": "所有spec项已勾选",
        "steps_en": "Step 1: Read spec.md. Implement the first unchecked item. Verify. Check [ x ].",
        "steps_zh": "Step 1: 读取spec.md。实现第一个未勾选的项目。验证。打勾[ x ]。",
        "max_iterations": "20",
    },
    # Code Quality (4)
    {
        "slug": "lint-typecheck-fix",
        "title_en": "Lint Typecheck Fix",
        "title_zh": "Lint和Typecheck修复",
        "category": "Code Quality",
        "goal_en": "lint and typecheck clean",
        "goal_zh": "lint和typecheck干净",
        "check_cmd": "npm run lint && npx tsc --noEmit",
        "exit_when_en": "lint and typecheck exit 0",
        "exit_when_zh": "lint和typecheck退出码为0",
        "steps_en": "Step 1: Run lint and typecheck. Fix reported issues with minimal diff.",
        "steps_zh": "Step 1: 运行lint和typecheck。用最小diff修复报告的问题。",
        "max_iterations": "5",
    },
    {
        "slug": "format-until-clean",
        "title_en": "Format Until Clean",
        "title_zh": "格式化直到干净",
        "category": "Code Quality",
        "goal_en": "formatter runs clean",
        "goal_zh": "格式化工具运行干净",
        "check_cmd": "npm run format",
        "exit_when_en": "format exits 0",
        "exit_when_zh": "格式化退出码为0",
        "steps_en": "Step 1: Run formatter. Fix what it cannot fix automatically.",
        "steps_zh": "Step 1: 运行格式化工具。修复它无法自动修复的问题。",
        "max_iterations": "3",
    },
    {
        "slug": "de-sloppify-pass",
        "title_en": "De-Sloppify Pass",
        "title_zh": "代码整洁检查",
        "category": "Code Quality",
        "goal_en": "recent changes are clean and minimal",
        "goal_zh": "最近的变更干净、最小化",
        "check_cmd": "npm run lint && npm test",
        "exit_when_en": "no sloppiness found",
        "exit_when_zh": "无脏代码",
        "steps_en": "Step 1: Review diff for debugging code, dead branches, naming issues.",
        "steps_zh": "Step 1: 审查diff中的调试代码、死分支、命名问题。",
        "max_iterations": "3",
    },
    {
        "slug": "knip-until-clean",
        "title_en": "Knip Until Clean",
        "title_zh": "Knip清理",
        "category": "Code Quality",
        "goal_en": "knip reports no unused code or deps",
        "goal_zh": "knip报告没有未使用代码或依赖",
        "check_cmd": "npx knip",
        "exit_when_en": "knip exits 0",
        "exit_when_zh": "knip退出码为0",
        "steps_en": "Step 1: Run knip. Delete dead code and unused deps. Verify tests still pass.",
        "steps_zh": "Step 1: 运行knip。删除死代码和未使用依赖。验证测试仍然通过。",
        "max_iterations": "5",
    },
    # API/Specs (2)
    {
        "slug": "api-contract-until-match",
        "title_en": "API Contract Until Match",
        "title_zh": "API契约匹配",
        "category": "API/Specs",
        "goal_en": "API implementation matches published contract",
        "goal_zh": "API实现与发布的契约匹配",
        "check_cmd": "npm run test:contract",
        "exit_when_en": "contract tests pass",
        "exit_when_zh": "契约测试通过",
        "steps_en": "Step 1: Run contract tests. Fix each schema/response mismatch with minimal diff.",
        "steps_zh": "Step 1: 运行契约测试。用最小diff修复每个schema/response不匹配。",
        "max_iterations": "10",
    },
    {
        "slug": "openapi-sync-until-valid",
        "title_en": "OpenAPI Sync Until Valid",
        "title_zh": "OpenAPI同步",
        "category": "API/Specs",
        "goal_en": "openapi.yaml lint clean and matches implemented routes",
        "goal_zh": "openapi.yaml lint干净且与实现的路由匹配",
        "check_cmd": "npx @redocly/cli lint openapi.yaml",
        "exit_when_en": "openapi lint exits 0",
        "exit_when_zh": "openapi lint退出码为0",
        "steps_en": "Step 1: Lint openapi.yaml. Fix spec errors and handler drift.",
        "steps_zh": "Step 1: Lint openapi.yaml。修复spec错误和处理程序漂移。",
        "max_iterations": "10",
    },
    # Dependencies (4)
    {
        "slug": "dependency-upgrade-one-by-one",
        "title_en": "Dependency Upgrade One By One",
        "title_zh": "依赖逐个升级",
        "category": "Dependencies",
        "goal_en": "critical outdated deps upgraded and tests green",
        "goal_zh": "关键过时依赖升级且测试绿色",
        "check_cmd": "npm outdated && npm test && npm run build",
        "exit_when_en": "outdated deps upgraded and all green",
        "exit_when_zh": "过时依赖已升级且全部绿色",
        "steps_en": "Step 1: Pick an outdated package. Upgrade it. Fix breaking changes. Commit.",
        "steps_zh": "Step 1: 选择一个过时的包。升级它。修复破坏性变更。提交。",
        "max_iterations": "10",
    },
    {
        "slug": "migration-until-applied",
        "title_en": "Migration Until Applied",
        "title_zh": "迁移直到应用",
        "category": "Dependencies",
        "goal_en": "all database migrations applied clean",
        "goal_zh": "所有数据库迁移应用干净",
        "check_cmd": "npx prisma migrate status",
        "exit_when_en": "migrations applied",
        "exit_when_zh": "迁移已应用",
        "steps_en": "Step 1: Run migrations. Fix schema or SQL errors.",
        "steps_zh": "Step 1: 运行迁移。修复schema或SQL错误。",
        "max_iterations": "5",
    },
    {
        "slug": "dependency-audit-weekly",
        "title_en": "Dependency Audit Weekly",
        "title_zh": "每周依赖审计",
        "category": "Dependencies",
        "goal_en": "deliver weekly dependency audit summary",
        "goal_zh": "交付每周依赖审计摘要",
        "check_cmd": "npm outdated || true",
        "exit_when_en": "outdated report delivered",
        "exit_when_zh": "过期报告已交付",
        "steps_en": "Step 1: Run npm outdated. Categorize updates. Suggest security upgrade plan.",
        "steps_zh": "Step 1: 运行npm outdated。按类别更新。建议安全升级计划。",
        "max_iterations": "1",
    },
    {
        "slug": "npm-audit-fix-loop",
        "title_en": "NPM Audit Fix Loop",
        "title_zh": "NPM审计修复循环",
        "category": "Dependencies",
        "goal_en": "no high or critical npm audit vulnerabilities",
        "goal_zh": "没有高危或严重npm审计漏洞",
        "check_cmd": "npm audit --audit-level=high && npm test",
        "exit_when_en": "no vulnerabilities found",
        "exit_when_zh": "无漏洞",
        "steps_en": "Step 1: Pick a high/critical advisory. Apply the safest fix.",
        "steps_zh": "Step 1: 选择一个高危/严重advisory。应用最安全的修复。",
        "max_iterations": "10",
    },
    # Security (1)
    {
        "slug": "security-audit-weekly",
        "title_en": "Security Audit Weekly",
        "title_zh": "每周安全审计",
        "category": "Security",
        "goal_en": "deliver weekly npm audit summary and fix plan",
        "goal_zh": "交付每周npm审计摘要和修复计划",
        "check_cmd": "npm audit --json",
        "exit_when_en": "audit summary delivered",
        "exit_when_zh": "审计摘要已交付",
        "steps_en": "Step 1: Run npm audit. Categorize by severity. Suggest fix steps.",
        "steps_zh": "Step 1: 运行npm audit。按严重性分类。建议修复步骤。",
        "max_iterations": "1",
    },
    # Development Process (5)
    {
        "slug": "autoloop-tdd",
        "title_en": "Autoloop TDD",
        "title_zh": "自动TDD循环",
        "category": "Development Process",
        "goal_en": "implement target behavior test-first",
        "goal_zh": "测试优先地实现目标行为",
        "check_cmd": "npm test",
        "exit_when_en": "behavior implemented and tested",
        "exit_when_zh": "行为已实现并测试",
        "steps_en": "Step 1: Write a failing test for the next behavior. Implement minimal code to pass. Refactor.",
        "steps_zh": "Step 1: 为下一个行为写一个失败的测试。实现最小代码通过。重构。",
        "max_iterations": "20",
    },
    {
        "slug": "changelog-sync-after-ship",
        "title_en": "Changelog Sync After Ship",
        "title_zh": "Changelog同步",
        "category": "Development Process",
        "goal_en": "CHANGELOG.md has accurate [Unreleased] entries",
        "goal_zh": "CHANGELOG.md有准确的[Unreleased]条目",
        "check_cmd": "git log -5 --oneline",
        "exit_when_en": "changelog updated",
        "exit_when_zh": "changelog已更新",
        "steps_en": "Step 1: Review recent commits. Write Keep-a-Changelog entries for user-visible changes.",
        "steps_zh": "Step 1: 审查最近提交。为用户可见的变更写Keep-a-Changelog条目。",
        "max_iterations": "1",
    },
    {
        "slug": "investigation-script-loop",
        "title_en": "Investigation Script Loop",
        "title_zh": "调查脚本循环",
        "category": "Development Process",
        "goal_en": "prove root cause with minimal repro script",
        "goal_zh": "用最小复现脚本证明根因",
        "check_cmd": "node scripts/investigate.mjs",
        "exit_when_en": "root cause reproduced",
        "exit_when_zh": "根因已复现",
        "steps_en": "Step 1: Write a small temporary script to reproduce the issue. Run it. Iterate output.",
        "steps_zh": "Step 1: 写一个小的临时脚本来复现问题。运行它。迭代输出。",
        "max_iterations": "10",
    },
    {
        "slug": "ralph-story-executor",
        "title_en": "Ralph Story Executor",
        "title_zh": "Ralph故事执行器",
        "category": "Development Process",
        "goal_en": "every story has passes: true",
        "goal_zh": "每个story都有passes: true",
        "check_cmd": "npm test && npm run lint && npm run build",
        "exit_when_en": "all stories pass",
        "exit_when_zh": "所有story通过",
        "steps_en": "Step 1: Read .rhal/prd.json. Pick an incomplete story. Implement it. Update status.",
        "steps_zh": "Step 1: 读取.rhal/prd.json。选择一个未完成的story。实现它。更新状态。",
        "max_iterations": "20",
    },
    {
        "slug": "reflexion-debug-loop",
        "title_en": "Reflexion Debug Loop",
        "title_zh": "Reflexion调试循环",
        "category": "Development Process",
        "goal_en": "failing test or repro passes",
        "goal_zh": "失败的测试或复现通过",
        "check_cmd": "npm test -- --testNamePattern=<test>",
        "exit_when_en": "test or repro passes",
        "exit_when_zh": "测试或复现通过",
        "steps_en": "Step 1: Reproduce bug. If failing, record in reflexion file, then try new fix.",
        "steps_zh": "Step 1: 复现bug。如果失败则在反思文件中记录后再尝试新修复。",
        "max_iterations": "10",
    },
    # Documentation (1)
    {
        "slug": "docs-sync-after-edits",
        "title_en": "Docs Sync After Edits",
        "title_zh": "文档同步",
        "category": "Documentation",
        "goal_en": "documentation matches current code changes",
        "goal_zh": "文档与当前代码变更匹配",
        "check_cmd": "git diff main...HEAD --name-only",
        "exit_when_en": "docs match code",
        "exit_when_zh": "文档与代码一致",
        "steps_en": "Step 1: Review diff. Find outdated docs. Update them.",
        "steps_zh": "Step 1: 审查diff。找到过时的文档。更新它们。",
        "max_iterations": "5",
    },
    # Performance (1)
    {
        "slug": "bundle-size-budget",
        "title_en": "Bundle Size Budget",
        "title_zh": "Bundle大小预算",
        "category": "Performance",
        "goal_en": "client bundle stays within budget",
        "goal_zh": "客户端bundle保持在预算内",
        "check_cmd": "npm run build && npm run size-limit",
        "exit_when_en": "bundle within budget",
        "exit_when_zh": "bundle在预算内",
        "steps_en": "Step 1: Build and measure bundle size. Lazy load or cut deps if over budget.",
        "steps_zh": "Step 1: 构建并测量bundle大小。如果超过预算则懒加载或削减依赖。",
        "max_iterations": "5",
    },
    # Accessibility (1)
    {
        "slug": "a11y-audit-until-clean",
        "title_en": "A11y Audit Until Clean",
        "title_zh": "无障碍审计",
        "category": "Accessibility",
        "goal_en": "no severe accessibility violations on changed UI",
        "goal_zh": "变更的UI上没有严重的无障碍访问违规",
        "check_cmd": "npm run test:a11y",
        "exit_when_en": "no a11y violations",
        "exit_when_zh": "无a11y违规",
        "steps_en": "Step 1: Run a11y audit on changed routes. Fix each violation.",
        "steps_zh": "Step 1: 在变更的路由上运行a11y审计。修复每个违规。",
        "max_iterations": "10",
    },
    # Pull Request (2)
    {
        "slug": "merge-conflict-resolver",
        "title_en": "Merge Conflict Resolver",
        "title_zh": "合并冲突解决",
        "category": "Pull Request",
        "goal_en": "branch rebases on main clean with passing tests",
        "goal_zh": "分支在main上rebase成功且测试通过",
        "check_cmd": "npm test",
        "exit_when_en": "rebase clean and tests pass",
        "exit_when_zh": "rebase成功且测试通过",
        "steps_en": "Step 1: Rebase on main. Resolve conflicts one file at a time. Run tests.",
        "steps_zh": "Step 1: 在main上rebase。一次一个文件解决冲突。运行测试。",
        "max_iterations": "10",
    },
    {
        "slug": "post-merge-regression-guard",
        "title_en": "Post-Merge Regression Guard",
        "title_zh": "合并后回归守卫",
        "category": "Pull Request",
        "goal_en": "smoke tests pass immediately after merge or rebase",
        "goal_zh": "每次合并或rebase后冒烟测试立即通过",
        "check_cmd": "npm run test:smoke",
        "exit_when_en": "smoke tests pass",
        "exit_when_zh": "冒烟测试通过",
        "steps_en": "Step 1: Run smoke tests after merge. Fix regressions before continuing other work.",
        "steps_zh": "Step 1: 合并后运行冒烟测试。在继续其他工作前修复回归。",
        "max_iterations": "3",
    },
    # Deployment (1)
    {
        "slug": "deploy-verification-loop",
        "title_en": "Deploy Verification Loop",
        "title_zh": "部署验证循环",
        "category": "Deployment",
        "goal_en": "all post-deploy health and smoke endpoints return success",
        "goal_zh": "所有部署后健康和冒烟端点返回成功",
        "check_cmd": "curl -fsS <your-health-url>",
        "exit_when_en": "endpoints return 0",
        "exit_when_zh": "端点返回0",
        "steps_en": "Step 1: Hit health/smoke URLs. If failing, check deployment logs.",
        "steps_zh": "Step 1: 访问健康/冒烟URL。如果失败则检查部署日志。",
        "max_iterations": "5",
    },
    # Maintenance (1)
    {
        "slug": "independent-verifier-pass",
        "title_en": "Independent Verifier Pass",
        "title_zh": "独立验证通过",
        "category": "Maintenance",
        "goal_en": "build, lint, and tests pass under independent verification",
        "goal_zh": "构建、lint和测试在独立验证下通过",
        "check_cmd": "npm run build && npm run lint && npm test",
        "exit_when_en": "all verifications pass",
        "exit_when_zh": "所有验证通过",
        "steps_en": "Step 1: Run build, lint, and tests as verifier. Trust only command output.",
        "steps_zh": "Step 1: 作为验证者运行构建、lint和测试。只信任命令输出。",
        "max_iterations": "1",
    },
    # Git Hooks (1)
    {
        "slug": "guardrails-learning-loop",
        "title_en": "Guardrails Learning Loop",
        "title_zh": "Guardrails学习循环",
        "category": "Git Hooks",
        "goal_en": "tests and lint pass without repeating previous failure patterns",
        "goal_zh": "测试和lint通过且不重复之前的失败模式",
        "check_cmd": "npm test && npm run lint",
        "exit_when_en": "checks pass without repeat failures",
        "exit_when_zh": "检查通过且无重复失败",
        "steps_en": "Step 1: Read guardrails.md. Run checks. If failing repeatedly, log then fix.",
        "steps_zh": "Step 1: 读取guardrails.md。运行检查。如果失败重复则记录再修复。",
        "max_iterations": "5",
    },

    # === New 60 Loops ===
    # Code Generation (8)
    {
        "slug": "code-review-until-clean",
        "title_en": "Code Review Until Clean",
        "title_zh": "代码审查直到干净",
        "category": "Code Generation",
        "goal_en": "code passes structured review checklist",
        "goal_zh": "代码通过结构化审查清单",
        "check_cmd": "python scripts/review_checklist.py",
        "exit_when_en": "all review checks pass",
        "exit_when_zh": "所有审查检查通过",
        "steps_en": "Step 1: Run review checklist. Fix each flagged issue. Repeat until clean.",
        "steps_zh": "Step 1: 运行审查清单。修复每个标记的问题。重复直到干净。",
        "max_iterations": "5",
    },
    {
        "slug": "refactor-until-clean",
        "title_en": "Refactor Until Clean",
        "title_zh": "重构直到干净",
        "category": "Code Generation",
        "goal_en": "target module meets clean code standards",
        "goal_zh": "目标模块达到整洁代码标准",
        "check_cmd": "npm run lint && npm test",
        "exit_when_en": "lint and tests pass with improved metrics",
        "exit_when_zh": "lint和测试通过且指标改善",
        "steps_en": "Step 1: Identify one smell. Refactor. Run checks. Repeat until metrics improve.",
        "steps_zh": "Step 1: 识别一个坏味道。重构。运行检查。重复直到指标改善。",
        "max_iterations": "10",
    },
    {
        "slug": "generate-unit-tests",
        "title_en": "Generate Unit Tests",
        "title_zh": "生成单元测试",
        "category": "Code Generation",
        "goal_en": "target function has passing unit tests for edge cases",
        "goal_zh": "目标函数对边界条件有通过的单元测试",
        "check_cmd": "npm test -- <target-file>",
        "exit_when_en": "new tests pass and cover edge cases",
        "exit_when_zh": "新测试通过并覆盖边界条件",
        "steps_en": "Step 1: Analyze function. Generate tests for normal, edge, and error cases. Run. Fix.",
        "steps_zh": "Step 1: 分析函数。为正常、边界和错误情况生成测试。运行。修复。",
        "max_iterations": "5",
    },
    {
        "slug": "component-scaffold-loop",
        "title_en": "Component Scaffold Loop",
        "title_zh": "组件脚手架循环",
        "category": "Code Generation",
        "goal_en": "new UI component scaffolded with tests and stories",
        "goal_zh": "新UI组件已生成测试和stories",
        "check_cmd": "npm test -- <component-name>",
        "exit_when_en": "component files and tests exist and pass",
        "exit_when_zh": "组件文件和测试存在且通过",
        "steps_en": "Step 1: Generate component file, test, and story. Run tests. Fix issues.",
        "steps_zh": "Step 1: 生成组件文件、测试和story。运行测试。修复问题。",
        "max_iterations": "5",
    },
    {
        "slug": "api-endpoint-generator",
        "title_en": "API Endpoint Generator",
        "title_zh": "API端点生成器",
        "category": "Code Generation",
        "goal_en": "new API endpoint implemented with handler, route, and tests",
        "goal_zh": "新API端点已实现handler、路由和测试",
        "check_cmd": "npm run test:api",
        "exit_when_en": "endpoint tests pass",
        "exit_when_zh": "端点测试通过",
        "steps_en": "Step 1: Generate route, handler, and tests from spec. Run. Fix until pass.",
        "steps_zh": "Step 1: 根据spec生成路由、handler和测试。运行。修复直到通过。",
        "max_iterations": "8",
    },
    {
        "slug": "error-handling-audit",
        "title_en": "Error Handling Audit",
        "title_zh": "错误处理审计",
        "category": "Code Generation",
        "goal_en": "all public functions have consistent error handling",
        "goal_zh": "所有公共函数有一致的错误处理",
        "check_cmd": "npm run lint && npm test",
        "exit_when_en": "no unhandled error patterns found",
        "exit_when_zh": "未发现未处理的错误模式",
        "steps_en": "Step 1: Scan for functions lacking error handling. Add consistent handling. Test.",
        "steps_zh": "Step 1: 扫描缺少错误处理的函数。添加一致的处理。测试。",
        "max_iterations": "8",
    },
    {
        "slug": "type-definition-sync",
        "title_en": "Type Definition Sync",
        "title_zh": "类型定义同步",
        "category": "Code Generation",
        "goal_en": "TypeScript types match runtime API and database schemas",
        "goal_zh": "TypeScript类型与运行时API和数据库schema匹配",
        "check_cmd": "npx tsc --noEmit",
        "exit_when_en": "typecheck passes without any cast",
        "exit_when_zh": "typecheck通过且无强制类型转换",
        "steps_en": "Step 1: Find mismatched types. Update definitions. Run typecheck. Repeat.",
        "steps_zh": "Step 1: 找到不匹配的type。更新定义。运行typecheck。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "dead-code-removal",
        "title_en": "Dead Code Removal",
        "title_zh": "死代码清理",
        "category": "Code Generation",
        "goal_en": "no unused exports, variables, or functions remain",
        "goal_zh": "无未使用的导出、变量或函数残留",
        "check_cmd": "npx knip --no-exit-code && npm test",
        "exit_when_en": "knip reports no dead code",
        "exit_when_zh": "knip报告无死代码",
        "steps_en": "Step 1: Run dead code analyzer. Remove or use flagged items. Test.",
        "steps_zh": "Step 1: 运行死代码分析器。删除或使用标记项。测试。",
        "max_iterations": "5",
    },
    # Database (5)
    {
        "slug": "schema-migration-loop",
        "title_en": "Schema Migration Loop",
        "title_zh": "Schema迁移循环",
        "category": "Database",
        "goal_en": "database schema change is migrated and tests pass",
        "goal_zh": "数据库schema变更已迁移且测试通过",
        "check_cmd": "npx prisma migrate dev && npm test",
        "exit_when_en": "migration applies cleanly and tests pass",
        "exit_when_zh": "迁移干净应用且测试通过",
        "steps_en": "Step 1: Update schema. Generate migration. Apply. Run tests. Fix issues.",
        "steps_zh": "Step 1: 更新schema。生成迁移。应用。运行测试。修复问题。",
        "max_iterations": "8",
    },
    {
        "slug": "query-performance-loop",
        "title_en": "Query Performance Loop",
        "title_zh": "查询性能循环",
        "category": "Database",
        "goal_en": "slow queries optimized below threshold",
        "goal_zh": "慢查询优化到阈值以下",
        "check_cmd": "npm run benchmark:queries",
        "exit_when_en": "all queries below threshold",
        "exit_when_zh": "所有查询低于阈值",
        "steps_en": "Step 1: Identify slowest query. Add index or rewrite. Benchmark. Repeat.",
        "steps_zh": "Step 1: 识别最慢的查询。添加索引或重写。基准测试。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "seed-data-validator",
        "title_en": "Seed Data Validator",
        "title_zh": "种子数据验证器",
        "category": "Database",
        "goal_en": "seed data loads cleanly and references are valid",
        "goal_zh": "种子数据干净加载且引用有效",
        "check_cmd": "npm run db:seed && npm run test:seed",
        "exit_when_en": "seed data loads without errors",
        "exit_when_zh": "种子数据无错误加载",
        "steps_en": "Step 1: Run seed script. Fix broken references or data issues. Repeat.",
        "steps_zh": "Step 1: 运行seed脚本。修复损坏的引用或数据问题。重复。",
        "max_iterations": "5",
    },
    {
        "slug": "backup-verify-loop",
        "title_en": "Backup Verify Loop",
        "title_zh": "备份验证循环",
        "category": "Database",
        "goal_en": "latest database backup restores successfully",
        "goal_zh": "最新数据库备份成功恢复",
        "check_cmd": "npm run db:backup:verify",
        "exit_when_en": "backup restores and basic queries pass",
        "exit_when_zh": "备份恢复且基本查询通过",
        "steps_en": "Step 1: Take backup. Restore to temp instance. Run smoke queries. Fix issues.",
        "steps_zh": "Step 1: 执行备份。恢复到临时实例。运行冒烟查询。修复问题。",
        "max_iterations": "3",
    },
    {
        "slug": "data-consistency-check",
        "title_en": "Data Consistency Check",
        "title_zh": "数据一致性检查",
        "category": "Database",
        "goal_en": "no orphaned records or constraint violations",
        "goal_zh": "无孤立记录或约束违规",
        "check_cmd": "npm run db:consistency",
        "exit_when_en": "all consistency checks pass",
        "exit_when_zh": "所有一致性检查通过",
        "steps_en": "Step 1: Run consistency checks. Fix each violation. Repeat until clean.",
        "steps_zh": "Step 1: 运行一致性检查。修复每个违规。重复直到干净。",
        "max_iterations": "5",
    },
    # Frontend (4)
    {
        "slug": "responsive-until-match",
        "title_en": "Responsive Until Match",
        "title_zh": "响应式直到匹配",
        "category": "Frontend",
        "goal_en": "UI renders correctly on all target breakpoints",
        "goal_zh": "UI在所有目标断点正确渲染",
        "check_cmd": "npx playwright test --grep @responsive",
        "exit_when_en": "responsive tests pass",
        "exit_when_zh": "响应式测试通过",
        "steps_en": "Step 1: Test each breakpoint. Fix layout issues. Repeat until all pass.",
        "steps_zh": "Step 1: 测试每个断点。修复布局问题。重复直到全部通过。",
        "max_iterations": "8",
    },
    {
        "slug": "design-token-sync",
        "title_en": "Design Token Sync",
        "title_zh": "设计Token同步",
        "category": "Frontend",
        "goal_en": "all UI uses approved design tokens",
        "goal_zh": "所有UI使用批准的设计token",
        "check_cmd": "npm run lint:design-tokens",
        "exit_when_en": "no hardcoded colors or spacing values",
        "exit_when_zh": "无硬编码颜色或间距值",
        "steps_en": "Step 1: Scan for hardcoded values. Replace with design tokens. Repeat.",
        "steps_zh": "Step 1: 扫描硬编码值。替换为设计token。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "component-library-update",
        "title_en": "Component Library Update",
        "title_zh": "组件库更新",
        "category": "Frontend",
        "goal_en": "component library updated with new variants and docs",
        "goal_zh": "组件库已更新新变体和文档",
        "check_cmd": "npm run storybook:build",
        "exit_when_en": "storybook builds successfully",
        "exit_when_zh": "storybook构建成功",
        "steps_en": "Step 1: Add component variant. Update story and docs. Build. Fix.",
        "steps_zh": "Step 1: 添加组件变体。更新story和文档。构建。修复。",
        "max_iterations": "8",
    },
    {
        "slug": "frontend-error-boundary-check",
        "title_en": "Frontend Error Boundary Check",
        "title_zh": "前端错误边界检查",
        "category": "Frontend",
        "goal_en": "all routes have error boundaries and fallback UI",
        "goal_zh": "所有路由都有错误边界和fallback UI",
        "check_cmd": "npm run lint:error-boundaries",
        "exit_when_en": "every route has error boundary coverage",
        "exit_when_zh": "每个路由都有错误边界覆盖",
        "steps_en": "Step 1: Audit routes. Add missing error boundaries. Test fallback UI.",
        "steps_zh": "Step 1: 审计路由。添加缺失的错误边界。测试fallback UI。",
        "max_iterations": "8",
    },
    # Backend (4)
    {
        "slug": "rate-limit-enforcer",
        "title_en": "Rate Limit Enforcer",
        "title_zh": "限流实施器",
        "category": "Backend",
        "goal_en": "all public endpoints enforce rate limits",
        "goal_zh": "所有公共端点都实施限流",
        "check_cmd": "npm run test:rate-limit",
        "exit_when_en": "rate limit tests pass",
        "exit_when_zh": "限流测试通过",
        "steps_en": "Step 1: Identify unprotected endpoints. Add rate limiting. Test.",
        "steps_zh": "Step 1: 识别未受保护端点。添加限流。测试。",
        "max_iterations": "8",
    },
    {
        "slug": "authz-policy-loop",
        "title_en": "Authz Policy Loop",
        "title_zh": "授权策略循环",
        "category": "Backend",
        "goal_en": "all sensitive endpoints enforce authorization",
        "goal_zh": "所有敏感端点都实施授权",
        "check_cmd": "npm run test:authz",
        "exit_when_en": "authorization tests pass",
        "exit_when_zh": "授权测试通过",
        "steps_en": "Step 1: Audit endpoints. Add authorization checks. Write tests. Repeat.",
        "steps_zh": "Step 1: 审计端点。添加授权检查。编写测试。重复。",
        "max_iterations": "10",
    },
    {
        "slug": "api-validation-loop",
        "title_en": "API Validation Loop",
        "title_zh": "API验证循环",
        "category": "Backend",
        "goal_en": "all API inputs validated and sanitized",
        "goal_zh": "所有API输入已验证和清理",
        "check_cmd": "npm run test:api-validation",
        "exit_when_en": "validation tests pass",
        "exit_when_zh": "验证测试通过",
        "steps_en": "Step 1: Find endpoints without validation. Add schema validation. Test.",
        "steps_zh": "Step 1: 找到无验证的端点。添加schema验证。测试。",
        "max_iterations": "8",
    },
    {
        "slug": "logging-audit-loop",
        "title_en": "Logging Audit Loop",
        "title_zh": "日志审计循环",
        "category": "Backend",
        "goal_en": "all critical paths produce structured logs",
        "goal_zh": "所有关键路径产生结构化日志",
        "check_cmd": "npm run lint:logging",
        "exit_when_en": "no unstructured log statements in critical paths",
        "exit_when_zh": "关键路径无非结构化日志语句",
        "steps_en": "Step 1: Audit critical paths. Replace unstructured logs. Test log output.",
        "steps_zh": "Step 1: 审计关键路径。替换非结构化日志。测试日志输出。",
        "max_iterations": "8",
    },
    # Data Science (6)
    {
        "slug": "data-cleaning-loop",
        "title_en": "Data Cleaning Loop",
        "title_zh": "数据清洗循环",
        "category": "Data Science",
        "goal_en": "dataset passes quality checks",
        "goal_zh": "数据集通过质量检查",
        "check_cmd": "python scripts/data_quality.py",
        "exit_when_en": "data quality checks pass",
        "exit_when_zh": "数据质量检查通过",
        "steps_en": "Step 1: Run quality checks. Fix missing values, outliers, duplicates. Repeat.",
        "steps_zh": "Step 1: 运行质量检查。修复缺失值、异常值、重复项。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "model-training-loop",
        "title_en": "Model Training Loop",
        "title_zh": "模型训练循环",
        "category": "Data Science",
        "goal_en": "model reaches target accuracy on validation set",
        "goal_zh": "模型在验证集上达到目标准确率",
        "check_cmd": "python scripts/train.py --validate",
        "exit_when_en": "validation accuracy meets target",
        "exit_when_zh": "验证准确率达标",
        "steps_en": "Step 1: Train model. Evaluate. Tune hyperparameters. Repeat until target met.",
        "steps_zh": "Step 1: 训练模型。评估。调整超参数。重复直到达标。",
        "max_iterations": "20",
    },
    {
        "slug": "feature-engineering-loop",
        "title_en": "Feature Engineering Loop",
        "title_zh": "特征工程循环",
        "category": "Data Science",
        "goal_en": "feature set improves model performance",
        "goal_zh": "特征集提升模型性能",
        "check_cmd": "python scripts/evaluate_features.py",
        "exit_when_en": "model score improves with new features",
        "exit_when_zh": "模型分数随新特征提升",
        "steps_en": "Step 1: Engineer one feature. Evaluate impact. Keep if score improves.",
        "steps_zh": "Step 1: 设计一个特征。评估影响。如果分数提升则保留。",
        "max_iterations": "15",
    },
    {
        "slug": "data-pipeline-until-green",
        "title_en": "Data Pipeline Until Green",
        "title_zh": "数据管道直到绿色",
        "category": "Data Science",
        "goal_en": "data pipeline runs end-to-end without errors",
        "goal_zh": "数据管道端到端无错误运行",
        "check_cmd": "python scripts/run_pipeline.py",
        "exit_when_en": "pipeline completes successfully",
        "exit_when_zh": "管道成功完成",
        "steps_en": "Step 1: Run pipeline. Fix first failure. Repeat until completion.",
        "steps_zh": "Step 1: 运行管道。修复第一个失败。重复直到完成。",
        "max_iterations": "10",
    },
    {
        "slug": "experiment-tracker",
        "title_en": "Experiment Tracker",
        "title_zh": "实验追踪器",
        "category": "Data Science",
        "goal_en": "experiment results logged and reproducible",
        "goal_zh": "实验结果已记录且可复现",
        "check_cmd": "python scripts/check_experiments.py",
        "exit_when_en": "all experiments have metadata and outputs",
        "exit_when_zh": "所有实验都有元数据和输出",
        "steps_en": "Step 1: Run missing experiments. Log params and metrics. Verify reproducibility.",
        "steps_zh": "Step 1: 运行缺失的实验。记录参数和指标。验证可复现性。",
        "max_iterations": "8",
    },
    {
        "slug": "dashboard-sync-loop",
        "title_en": "Dashboard Sync Loop",
        "title_zh": "仪表盘同步循环",
        "category": "Data Science",
        "goal_en": "dashboard reflects latest data and metrics",
        "goal_zh": "仪表盘反映最新数据和指标",
        "check_cmd": "python scripts/refresh_dashboard.py",
        "exit_when_en": "dashboard data is up to date",
        "exit_when_zh": "仪表盘数据已更新",
        "steps_en": "Step 1: Refresh dashboard. Fix broken queries or stale caches. Repeat.",
        "steps_zh": "Step 1: 刷新仪表盘。修复损坏的查询或过时的缓存。重复。",
        "max_iterations": "5",
    },
    # Content Creation (7)
    {
        "slug": "blog-post-until-publish",
        "title_en": "Blog Post Until Publish",
        "title_zh": "博客文章直到发布",
        "category": "Content Creation",
        "goal_en": "blog post is polished and ready to publish",
        "goal_zh": "博客文章已润色并准备发布",
        "check_cmd": "python scripts/blog_quality.py draft.md",
        "exit_when_en": "quality score meets threshold",
        "exit_when_zh": "质量分数达标",
        "steps_en": "Step 1: Check structure, clarity, SEO. Revise one issue. Repeat.",
        "steps_zh": "Step 1: 检查结构、清晰度、SEO。修改一个问题。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "readme-improvement-loop",
        "title_en": "README Improvement Loop",
        "title_zh": "README改进循环",
        "category": "Content Creation",
        "goal_en": "README is clear, complete, and follows best practices",
        "goal_zh": "README清晰、完整并遵循最佳实践",
        "check_cmd": "python scripts/readme_lint.py",
        "exit_when_en": "README lint passes",
        "exit_when_zh": "README lint通过",
        "steps_en": "Step 1: Lint README. Fix one issue (heading, example, badge). Repeat.",
        "steps_zh": "Step 1: Lint README。修复一个问题（标题、示例、徽章）。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "social-post-generator",
        "title_en": "Social Post Generator",
        "title_zh": "社媒帖子生成器",
        "category": "Content Creation",
        "goal_en": "social media posts generated for each platform",
        "goal_zh": "为每个平台生成社交媒体帖子",
        "check_cmd": "python scripts/check_posts.py",
        "exit_when_en": "posts generated for all target platforms",
        "exit_when_zh": "已为所有目标平台生成帖子",
        "steps_en": "Step 1: Generate one platform post. Check length and tone. Repeat for each.",
        "steps_zh": "Step 1: 生成一个平台的帖子。检查长度和语气。为每个平台重复。",
        "max_iterations": "10",
    },
    {
        "slug": "newsletter-until-send",
        "title_en": "Newsletter Until Send",
        "title_zh": "Newsletter直到发送",
        "category": "Content Creation",
        "goal_en": "newsletter passes review and links are valid",
        "goal_zh": "Newsletter通过审查且链接有效",
        "check_cmd": "python scripts/newsletter_check.py",
        "exit_when_en": "all links valid and content reviewed",
        "exit_when_zh": "所有链接有效且内容已审查",
        "steps_en": "Step 1: Check links. Review content. Fix issues. Repeat.",
        "steps_zh": "Step 1: 检查链接。审查内容。修复问题。重复。",
        "max_iterations": "5",
    },
    {
        "slug": "video-script-loop",
        "title_en": "Video Script Loop",
        "title_zh": "视频脚本循环",
        "category": "Content Creation",
        "goal_en": "video script meets target duration and clarity",
        "goal_zh": "视频脚本达到目标时长和清晰度",
        "check_cmd": "python scripts/script_review.py",
        "exit_when_en": "script passes review",
        "exit_when_zh": "脚本通过审查",
        "steps_en": "Step 1: Review script for duration, clarity, hooks. Revise. Repeat.",
        "steps_zh": "Step 1: 审查脚本的时长、清晰度、钩子。修改。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "translation-review-loop",
        "title_en": "Translation Review Loop",
        "title_zh": "翻译审校循环",
        "category": "Content Creation",
        "goal_en": "translation is accurate and natural",
        "goal_zh": "翻译准确自然",
        "check_cmd": "python scripts/translation_check.py",
        "exit_when_en": "translation review passes",
        "exit_when_zh": "翻译审查通过",
        "steps_en": "Step 1: Check segment. Fix mistranslation or awkward phrasing. Repeat.",
        "steps_zh": "Step 1: 检查片段。修复误译或生硬表达。重复。",
        "max_iterations": "10",
    },
    {
        "slug": "ad-copy-optimizer",
        "title_en": "Ad Copy Optimizer",
        "title_zh": "广告文案优化器",
        "category": "Content Creation",
        "goal_en": "ad copy variants meet conversion checklist",
        "goal_zh": "广告文案变体通过转化检查清单",
        "check_cmd": "python scripts/ad_copy_check.py",
        "exit_when_en": "all variants pass checklist",
        "exit_when_zh": "所有变体通过检查清单",
        "steps_en": "Step 1: Generate variants. Check against checklist. Improve one. Repeat.",
        "steps_zh": "Step 1: 生成变体。对照检查清单检查。改进一个。重复。",
        "max_iterations": "10",
    },
    # Product & Design (4)
    {
        "slug": "prd-review-loop",
        "title_en": "PRD Review Loop",
        "title_zh": "PRD审查循环",
        "category": "Product & Design",
        "goal_en": "PRD is complete, clear, and ready for development",
        "goal_zh": "PRD完整、清晰并准备开发",
        "check_cmd": "python scripts/prd_check.py",
        "exit_when_en": "PRD passes all review checks",
        "exit_when_zh": "PRD通过所有审查检查",
        "steps_en": "Step 1: Check PRD sections. Fill gaps. Clarify requirements. Repeat.",
        "steps_zh": "Step 1: 检查PRD章节。填补空白。澄清需求。重复。",
        "max_iterations": "6",
    },
    {
        "slug": "user-story-generator",
        "title_en": "User Story Generator",
        "title_zh": "用户故事生成器",
        "category": "Product & Design",
        "goal_en": "user stories generated for each feature",
        "goal_zh": "为每个功能生成用户故事",
        "check_cmd": "python scripts/story_check.py",
        "exit_when_en": "all features have stories with acceptance criteria",
        "exit_when_zh": "所有功能都有带验收标准的用户故事",
        "steps_en": "Step 1: Pick feature. Write story with acceptance criteria. Validate. Repeat.",
        "steps_zh": "Step 1: 选择功能。编写带验收标准的用户故事。验证。重复。",
        "max_iterations": "15",
    },
    {
        "slug": "design-review-loop",
        "title_en": "Design Review Loop",
        "title_zh": "设计审查循环",
        "category": "Product & Design",
        "goal_en": "design follows system guidelines and accessibility rules",
        "goal_zh": "设计遵循系统规范和无障碍规则",
        "check_cmd": "python scripts/design_check.py",
        "exit_when_en": "design review passes",
        "exit_when_zh": "设计审查通过",
        "steps_en": "Step 1: Check tokens, spacing, accessibility. Fix one issue. Repeat.",
        "steps_zh": "Step 1: 检查token、间距、无障碍。修复一个问题。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "competitive-analysis-loop",
        "title_en": "Competitive Analysis Loop",
        "title_zh": "竞品分析循环",
        "category": "Product & Design",
        "goal_en": "competitive analysis report is complete and sourced",
        "goal_zh": "竞品分析报告完整且有来源",
        "check_cmd": "python scripts/competitor_check.py",
        "exit_when_en": "report has all required sections and sources",
        "exit_when_zh": "报告包含所有必需章节和来源",
        "steps_en": "Step 1: Research competitor. Add section with sources. Validate. Repeat.",
        "steps_zh": "Step 1: 研究竞品。添加带来源的章节。验证。重复。",
        "max_iterations": "10",
    },
    # Operations & Marketing (4)
    {
        "slug": "seo-audit-loop",
        "title_en": "SEO Audit Loop",
        "title_zh": "SEO审计循环",
        "category": "Operations & Marketing",
        "goal_en": "page passes SEO checklist",
        "goal_zh": "页面通过SEO检查清单",
        "check_cmd": "python scripts/seo_check.py",
        "exit_when_en": "SEO score meets target",
        "exit_when_zh": "SEO分数达标",
        "steps_en": "Step 1: Audit meta, headings, links, speed. Fix highest impact issue. Repeat.",
        "steps_zh": "Step 1: 审计meta、标题、链接、速度。修复影响最大的问题。重复。",
        "max_iterations": "10",
    },
    {
        "slug": "email-campaign-loop",
        "title_en": "Email Campaign Loop",
        "title_zh": "邮件营销循环",
        "category": "Operations & Marketing",
        "goal_en": "email campaign is reviewed and links valid",
        "goal_zh": "邮件营销活动已审查且链接有效",
        "check_cmd": "python scripts/email_check.py",
        "exit_when_en": "campaign passes review and link check",
        "exit_when_zh": "营销活动通过审查和链接检查",
        "steps_en": "Step 1: Check subject, body, links, compliance. Fix. Repeat.",
        "steps_zh": "Step 1: 检查主题、正文、链接、合规性。修复。重复。",
        "max_iterations": "5",
    },
    {
        "slug": "analytics-health-check",
        "title_en": "Analytics Health Check",
        "title_zh": "分析健康检查",
        "category": "Operations & Marketing",
        "goal_en": "all key events tracked correctly",
        "goal_zh": "所有关键事件正确追踪",
        "check_cmd": "python scripts/analytics_check.py",
        "exit_when_en": "all events fire correctly",
        "exit_when_zh": "所有事件正确触发",
        "steps_en": "Step 1: Audit events. Fix missing or incorrect tracking. Test. Repeat.",
        "steps_zh": "Step 1: 审计事件。修复缺失或错误的追踪。测试。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "release-notes-generator",
        "title_en": "Release Notes Generator",
        "title_zh": "发布说明生成器",
        "category": "Operations & Marketing",
        "goal_en": "release notes are generated and reviewed",
        "goal_zh": "发布说明已生成并审查",
        "check_cmd": "python scripts/release_notes_check.py",
        "exit_when_en": "release notes complete and accurate",
        "exit_when_zh": "发布说明完整准确",
        "steps_en": "Step 1: Generate notes from commits. Review for user impact. Edit. Repeat.",
        "steps_zh": "Step 1: 根据提交生成说明。审查用户影响。编辑。重复。",
        "max_iterations": "5",
    },
    # Learning & Knowledge (5)
    {
        "slug": "flashcard-generator",
        "title_en": "Flashcard Generator",
        "title_zh": "闪卡生成器",
        "category": "Learning & Knowledge",
        "goal_en": "flashcards generated for key concepts",
        "goal_zh": "为关键概念生成闪卡",
        "check_cmd": "python scripts/flashcard_check.py",
        "exit_when_en": "all concepts have flashcards",
        "exit_when_zh": "所有概念都有闪卡",
        "steps_en": "Step 1: Extract concept. Create question/answer card. Validate. Repeat.",
        "steps_zh": "Step 1: 提取概念。创建问答闪卡。验证。重复。",
        "max_iterations": "20",
    },
    {
        "slug": "study-plan-optimizer",
        "title_en": "Study Plan Optimizer",
        "title_zh": "学习计划优化器",
        "category": "Learning & Knowledge",
        "goal_en": "study plan is realistic and covers all topics",
        "goal_zh": "学习计划现实并覆盖所有主题",
        "check_cmd": "python scripts/study_plan_check.py",
        "exit_when_en": "plan passes feasibility check",
        "exit_when_zh": "计划通过可行性检查",
        "steps_en": "Step 1: Check topic coverage and time allocation. Adjust. Repeat.",
        "steps_zh": "Step 1: 检查主题覆盖和时间分配。调整。重复。",
        "max_iterations": "5",
    },
    {
        "slug": "note-organizer",
        "title_en": "Note Organizer",
        "title_zh": "笔记整理器",
        "category": "Learning & Knowledge",
        "goal_en": "notes are tagged, linked, and well-structured",
        "goal_zh": "笔记已打标签、链接并结构良好",
        "check_cmd": "python scripts/note_check.py",
        "exit_when_en": "all notes organized and linked",
        "exit_when_zh": "所有笔记已整理并链接",
        "steps_en": "Step 1: Process one note. Add tags and links. Validate. Repeat.",
        "steps_zh": "Step 1: 处理一条笔记。添加标签和链接。验证。重复。",
        "max_iterations": "20",
    },
    {
        "slug": "research-synthesis-loop",
        "title_en": "Research Synthesis Loop",
        "title_zh": "研究综合循环",
        "category": "Learning & Knowledge",
        "goal_en": "research is summarized with sources and key insights",
        "goal_zh": "研究已总结来源和关键洞察",
        "check_cmd": "python scripts/research_check.py",
        "exit_when_en": "synthesis meets quality criteria",
        "exit_when_zh": "综合达到质量标准",
        "steps_en": "Step 1: Read source. Extract insight. Add to synthesis. Check. Repeat.",
        "steps_zh": "Step 1: 阅读来源。提取洞察。添加到综合。检查。重复。",
        "max_iterations": "15",
    },
    {
        "slug": "quiz-validator",
        "title_en": "Quiz Validator",
        "title_zh": "测验验证器",
        "category": "Learning & Knowledge",
        "goal_en": "quiz questions are accurate and have correct answers",
        "goal_zh": "测验问题准确且有正确答案",
        "check_cmd": "python scripts/quiz_check.py",
        "exit_when_en": "all quiz items validated",
        "exit_when_zh": "所有测验项已验证",
        "steps_en": "Step 1: Check question clarity and answer. Fix issues. Repeat.",
        "steps_zh": "Step 1: 检查问题清晰度和答案。修复问题。重复。",
        "max_iterations": "10",
    },
    # Productivity (4)
    {
        "slug": "meeting-notes-cleaner",
        "title_en": "Meeting Notes Cleaner",
        "title_zh": "会议纪要整理器",
        "category": "Productivity",
        "goal_en": "meeting notes are structured with action items",
        "goal_zh": "会议纪要结构化并含行动项",
        "check_cmd": "python scripts/meeting_check.py",
        "exit_when_en": "notes have summary, decisions, and action items",
        "exit_when_zh": "笔记包含摘要、决策和行动项",
        "steps_en": "Step 1: Format notes. Extract action items. Assign owners. Check.",
        "steps_zh": "Step 1: 格式化笔记。提取行动项。分配负责人。检查。",
        "max_iterations": "3",
    },
    {
        "slug": "inbox-zero-loop",
        "title_en": "Inbox Zero Loop",
        "title_zh": "收件箱清零循环",
        "category": "Productivity",
        "goal_en": "inbox has zero unread actionable emails",
        "goal_zh": "收件箱无未读可执行邮件",
        "check_cmd": "python scripts/inbox_check.py",
        "exit_when_en": "inbox is at zero actionable items",
        "exit_when_zh": "收件箱可执行项为零",
        "steps_en": "Step 1: Process one email: reply, archive, delegate, or schedule. Repeat.",
        "steps_zh": "Step 1: 处理一封邮件：回复、归档、委派或安排。重复。",
        "max_iterations": "50",
    },
    {
        "slug": "task-prioritizer",
        "title_en": "Task Prioritizer",
        "title_zh": "任务优先级排序器",
        "category": "Productivity",
        "goal_en": "tasks are prioritized by impact and effort",
        "goal_zh": "任务按影响力和工作量排序",
        "check_cmd": "python scripts/task_check.py",
        "exit_when_en": "all tasks have priority and estimation",
        "exit_when_zh": "所有任务都有优先级和估算",
        "steps_en": "Step 1: Review one task. Assign impact/effort. Reorder. Repeat.",
        "steps_zh": "Step 1: 审查一个任务。分配影响力/工作量。重新排序。重复。",
        "max_iterations": "20",
    },
    {
        "slug": "weekly-review-loop",
        "title_en": "Weekly Review Loop",
        "title_zh": "每周回顾循环",
        "category": "Productivity",
        "goal_en": "weekly review report is complete",
        "goal_zh": "每周回顾报告完成",
        "check_cmd": "python scripts/weekly_review_check.py",
        "exit_when_en": "review covers goals, tasks, and next week plan",
        "exit_when_zh": "回顾涵盖目标、任务和下周计划",
        "steps_en": "Step 1: Collect accomplishments, blockers, next steps. Compile report.",
        "steps_zh": "Step 1: 收集成就、阻塞、下一步。编写报告。",
        "max_iterations": "3",
    },
    # System & DevOps (5)
    {
        "slug": "docker-build-until-green",
        "title_en": "Docker Build Until Green",
        "title_zh": "Docker构建直到成功",
        "category": "System & DevOps",
        "goal_en": "Docker image builds and passes health check",
        "goal_zh": "Docker镜像构建并通过健康检查",
        "check_cmd": "docker build -t app . && docker run --rm app healthcheck",
        "exit_when_en": "image builds and healthcheck passes",
        "exit_when_zh": "镜像构建且健康检查通过",
        "steps_en": "Step 1: Build image. Fix Dockerfile issues. Run healthcheck. Repeat.",
        "steps_zh": "Step 1: 构建镜像。修复Dockerfile问题。运行健康检查。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "terraform-plan-until-clean",
        "title_en": "Terraform Plan Until Clean",
        "title_zh": "Terraform Plan直到干净",
        "category": "System & DevOps",
        "goal_en": "terraform plan has no unexpected changes",
        "goal_zh": "terraform plan无意外变更",
        "check_cmd": "terraform plan -detailed-exitcode",
        "exit_when_en": "plan is clean or expected",
        "exit_when_zh": "plan干净或符合预期",
        "steps_en": "Step 1: Run terraform plan. Review unexpected changes. Fix. Repeat.",
        "steps_zh": "Step 1: 运行terraform plan。审查意外变更。修复。重复。",
        "max_iterations": "8",
    },
    {
        "slug": "log-anomaly-detector",
        "title_en": "Log Anomaly Detector",
        "title_zh": "日志异常检测器",
        "category": "System & DevOps",
        "goal_en": "no critical anomalies in recent logs",
        "goal_zh": "近期日志无严重异常",
        "check_cmd": "python scripts/log_anomaly.py",
        "exit_when_en": "no critical anomalies detected",
        "exit_when_zh": "未检测到严重异常",
        "steps_en": "Step 1: Scan logs. Investigate anomalies. Fix root cause. Repeat.",
        "steps_zh": "Step 1: 扫描日志。调查异常。修复根因。重复。",
        "max_iterations": "10",
    },
    {
        "slug": "ssl-certificate-monitor",
        "title_en": "SSL Certificate Monitor",
        "title_zh": "SSL证书监控",
        "category": "System & DevOps",
        "goal_en": "all domains have valid SSL certificates",
        "goal_zh": "所有域名都有有效SSL证书",
        "check_cmd": "python scripts/ssl_check.py",
        "exit_when_en": "all certificates valid and not expiring soon",
        "exit_when_zh": "所有证书有效且未临近过期",
        "steps_en": "Step 1: Check each domain's certificate. Renew or fix expiring ones.",
        "steps_zh": "Step 1: 检查每个域名的证书。续期或修复即将过期的证书。",
        "max_iterations": "5",
    },
    {
        "slug": "backup-routine-loop",
        "title_en": "Backup Routine Loop",
        "title_zh": "备份例行循环",
        "category": "System & DevOps",
        "goal_en": "all critical data backed up and verified",
        "goal_zh": "所有关键数据已备份并验证",
        "check_cmd": "python scripts/backup_check.py",
        "exit_when_en": "all backups complete and verified",
        "exit_when_zh": "所有备份完成并验证",
        "steps_en": "Step 1: Run backup job. Verify integrity. Fix failures. Repeat.",
        "steps_zh": "Step 1: 运行备份任务。验证完整性。修复失败。重复。",
        "max_iterations": "5",
    },
    # Security & Compliance (4)
    {
        "slug": "secret-scan-loop",
        "title_en": "Secret Scan Loop",
        "title_zh": "密钥扫描循环",
        "category": "Security & Compliance",
        "goal_en": "no secrets or credentials in repository",
        "goal_zh": "仓库中无密钥或凭证",
        "check_cmd": "npx secretlint --maskSecrets \"**/*\"",
        "exit_when_en": "secret scan passes clean",
        "exit_when_zh": "密钥扫描通过",
        "steps_en": "Step 1: Run secret scan. Remove or rotate leaked secrets. Repeat.",
        "steps_zh": "Step 1: 运行密钥扫描。删除或轮换泄露的密钥。重复。",
        "max_iterations": "5",
    },
    {
        "slug": "compliance-checklist-loop",
        "title_en": "Compliance Checklist Loop",
        "title_zh": "合规检查清单循环",
        "category": "Security & Compliance",
        "goal_en": "all compliance checklist items are satisfied",
        "goal_zh": "所有合规检查项已满足",
        "check_cmd": "python scripts/compliance_check.py",
        "exit_when_en": "compliance score is 100%",
        "exit_when_zh": "合规分数为100%",
        "steps_en": "Step 1: Check one compliance item. Gather evidence or fix. Repeat.",
        "steps_zh": "Step 1: 检查一个合规项。收集证据或修复。重复。",
        "max_iterations": "15",
    },
    {
        "slug": "privacy-policy-audit",
        "title_en": "Privacy Policy Audit",
        "title_zh": "隐私政策审计",
        "category": "Security & Compliance",
        "goal_en": "privacy policy matches current data practices",
        "goal_zh": "隐私政策与当前数据实践匹配",
        "check_cmd": "python scripts/privacy_check.py",
        "exit_when_en": "policy audit passes",
        "exit_when_zh": "政策审计通过",
        "steps_en": "Step 1: Compare policy to data collection points. Update discrepancies.",
        "steps_zh": "Step 1: 将政策与数据收集点对比。更新差异。",
        "max_iterations": "5",
    },
    {
        "slug": "access-review-loop",
        "title_en": "Access Review Loop",
        "title_zh": "访问权限审查循环",
        "category": "Security & Compliance",
        "goal_en": "all user access permissions are justified",
        "goal_zh": "所有用户访问权限都有正当理由",
        "check_cmd": "python scripts/access_review.py",
        "exit_when_en": "all permissions reviewed and documented",
        "exit_when_zh": "所有权限已审查并记录",
        "steps_en": "Step 1: Review one user/role. Verify justification. Remove or document.",
        "steps_zh": "Step 1: 审查一个用户/角色。验证理由。删除或记录。",
        "max_iterations": "20",
    },
]

def generate_en_markdown(loop):
    return f"""---
name: "{loop['slug']}"
description: "{loop['goal_en']}"
---

# {loop['title_en']}

**Category:** {loop['category']}  
**Slug:** `{loop['slug']}`  
**Max Iterations:** {loop['max_iterations']}

## Goal

{loop['goal_en']}

## Check Command

```bash
{loop['check_cmd']}
```

## Exit Condition

{loop['exit_when_en']}

## Steps

{loop['steps_en']}

## Recommended Agents

Claude Code, Cursor, Trae, Windsurf, Cline
"""

def generate_zh_markdown(loop):
    return f"""---
name: "{loop['slug']}"
description: "{loop['goal_zh']}"
---

# {loop['title_zh']}

**分类:** {CATEGORY_ZH.get(loop['category'], loop['category'])}  
**标识符:** `{loop['slug']}`  
**最大迭代次数:** {loop['max_iterations']}

## 目标

{loop['goal_zh']}

## 检查命令

```bash
{loop['check_cmd']}
```

## 退出条件

{loop['exit_when_zh']}

## 执行步骤

{loop['steps_zh']}

## 推荐代理

Claude Code、Cursor、Trae、Windsurf、Cline
"""

def main():
    # Safety guard: this script regenerates the OLD 5-section minimal structure
    # and would OVERWRITE the hand-enhanced 8-section files in prompts/.
    # Require an explicit opt-in env var to proceed. See module docstring.
    if os.environ.get("LOOPS_REGENERATE") != "1":
        print(
            "⛔ Refusing to run: prompts/zh and prompts/en contain hand-enhanced\n"
            "   8-section files. This script would overwrite them with the old\n"
            "   5-section minimal structure.\n\n"
            "   This script is kept only as a legacy bootstrap for brand-new Loops.\n"
            "   To proceed anyway (DESTRUCTIVE), run:\n"
            "       LOOPS_REGENERATE=1 python3 generate_all_prompts.py",
            file=sys.stderr,
        )
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    en_dir = os.path.join(script_dir, "prompts", "en")
    zh_dir = os.path.join(script_dir, "prompts", "zh")

    os.makedirs(en_dir, exist_ok=True)
    os.makedirs(zh_dir, exist_ok=True)

    # Clear existing files to regenerate all
    for f in os.listdir(en_dir):
        if f.endswith('.md'):
            os.remove(os.path.join(en_dir, f))
    for f in os.listdir(zh_dir):
        if f.endswith('.md'):
            os.remove(os.path.join(zh_dir, f))

    total = 0
    for loop in ALL_LOOPS:
        slug = loop['slug']

        en_path = os.path.join(en_dir, f"{slug}.md")
        with open(en_path, "w", encoding="utf-8") as f:
            f.write(generate_en_markdown(loop))

        zh_path = os.path.join(zh_dir, f"{slug}.md")
        with open(zh_path, "w", encoding="utf-8") as f:
            f.write(generate_zh_markdown(loop))

        print(f"Generated: {slug}")
        total += 1

    print(f"\nTotal: {total} loops")

if __name__ == "__main__":
    main()
